### ISSUE TITLE
Add code examples of starting up workers for queue other than "default"

### ISSUE THREAD

**Issue by theoephraim** [jbielick/faktory_worker_node#10]
I see from the code that the cli has options for booting up workers on queues other than default, and even specifying weights.

Would be good to have more code examples in the readme for anyone not using the bin scripts

**Comment by tbonz** [comment]
Here's an example targeting a single queue and setting the concurrency to 1

```javascript
const faktory = require('faktory-worker');

faktory.register('MyDoWorkJob', async (id, size) => {
  const img = await Image.find(id);
  await resize(img.blob, size);
});

await faktory.work({
  queues: ['MyDoWorkQueue'],
  concurrency : 1
});
// send INT signal to shutdown gracefully
```

**Comment by jbielick** [comment]
Examples added! Thanks for the feedback.

**Comment by Deekor** [comment]
Im looking for an example of how to set a queue on a job im pushing and cant find it anywhere

**Comment by jbielick** [comment]
https://github.com/jbielick/faktory_worker_node/blob/main/docs/api.md#Job+queue
