### ISSUE TITLE
Need a way to downgrade "ERROR: faktory-worker:client:heart" logs to "DEBUG" or "INFO" level.

### ISSUE THREAD

**Issue by kumuvetti** [jbielick/faktory_worker_node#151]
We enabled all faktory-worker logs and now everytime a heart beat is sent, this shows up as an ERROR level log.
Exact message is: "ERROR: faktory-worker:client:heart" occuring every time a heart beat is sent (i.e., not indicative of an error, just that a heart beat was sent).

We would like a way to downgrade this heart beat sent log message to DEBUG or INFO.

**Comment by jbielick** [comment]
Hi, I'm not sure what faktory_worker_node version you're using, but that would help me look into this. Could you provide the details outlined in the issue template?

I'd also like to know how you're running the faktory worker process (what command, what environment variables are set) and what configuration options you're providing when doing so. The heartbeat should already by a DEBUG log. There are no log levels, DEBUG logs are either enabled or not based on patterns.

**Comment by kumuvetti** [comment]
The issues seems to be that DEBUG logs are going to stderr, which is considered as an error log by my cloud provider.

**Comment by DanielChanJA** [comment]
Updoot from me too.

**Comment by jbielick** [comment]
Simple fix here is to not enable debug logging in production. This is not the same as log_level=debug or something if that’s what you were expecting. These are for temporarily collecting info when finding or tracing a bug or issue.
