### ISSUE TITLE
[feature request] deno

### ISSUE THREAD

**Issue by melkir** [jbielick/faktory_worker_node#224]
I would love to see this project ported to deno.
There's actually an existing project but having both project maintained at the same place seems to me a better choice for the long term.

Here's a ressource that might help https://medium.com/samsung-internet-dev/using-node-modules-in-deno-2885600ed7a9

**Comment by jbielick** [comment]
What would you need from this library to allow it to work in deno?

**Comment by melkir** [comment]
Hello @jbielick, regarding the latest compatibility from https://deno.land/std@0.119.0/node/README.md, it might work as it 😄

**Comment by jcs224** [comment]
Great news, it seems to work in Deno now using the latest stuff!

`std/node` version: 0.125.0
Deno version: 1.18.2

Run this command for the job pusher: `deno run --allow-read --allow-env --allow-net --unstable faktory.js` 
```js
// faktory.js
import { createRequire } from "https://deno.land/std@0.125.0/node/module.ts";
const require = createRequire(import.meta.url);

const faktory = require('faktory-worker');

try {
  const client = await faktory.connect();
  await client.job("ResizeImage", { id: 333, size: "thumb" }).push();
  await client.close(); // reuse client if possible! remember to disconnect!
} catch (e) {
  console.error(e);
}

console.log('finished');
```
Run this for the worker: `deno run --allow-read --allow-env --allow-net --unstable faktory.js`
(delayed by one second to show that promises work)
```js
//faktory-worker.js
import { createRequire } from "https://deno.land/std@0.125.0/node/module.ts";
const require = createRequire(import.meta.url);

const faktory = require('faktory-worker');

faktory.register("ResizeImage", async ({ id, size }) => {
  await new Promise((resolve) => {
    setTimeout(() => {
      console.log('waiting for id of ',id,' and size ',size);
      resolve();
    }, 1000);
  });
});

faktory.work().catch(error => {
  console.error(`worker failed to start: ${error}`);
  process.exit(1);
});
```
[jbielick](https://github.com/jbielick) it looks like there is enough Node compatibility to finally make this thing work! It would be cool to consider it a supported platform, and I will deprecate my own Deno-specific library. It is not nearly as feature-rich or stable as this project :sweat_smile:

**Comment by melkir** [comment]
Here's what I would recommend for Deno on latest versions.


```ts
// producer.ts
import { Client as FaktoryClient } from "npm:faktory-worker";

const client = new FaktoryClient();
await client.connect();

const job = client.job("ResizeImage", { id: 333, size: "thumb" });
await job.push();

await client.close()
```

```ts
// receiver.ts
import { Worker as FaktoryWorker } from "npm:faktory-worker";

const worker = new FaktoryWorker();

worker.register("ResizeImage", async ({ id, size }) => {
  const image = await Image.find(id);
  await image.resize(size);
});

try {
  await worker.work();
} catch (error: unknown) {
  console.error(`worker failed to start: ${error}`);
  Deno.exit(1);
}
```

If you have an example of usage, I have a project that I recently migrated to this dependency.
https://github.com/melkir/dsn-validator
⚠️ Please note that this code is still being tested, so please do not use it in production.
