### ISSUE TITLE
Socket closed unexpectedly

### ISSUE THREAD

**Issue by jbielick** [jbielick/faktory_worker_node#24]
using faktory 0.9.1 docker

Error: Socket closed unexpectedly
    at Client.onClose (/reporter/node_modules/faktory-worker/lib/client.js:346:20)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at TCP._handle.close (net.js:599:12)
(node:48) UnhandledPromiseRejectionWarning: TypeError: this.onConnectReject is not a function
    at Client.onConnect (/reporter/node_modules/faktory-worker/lib/client.js:318:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:48) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originate

**Comment by jbielick** [comment]
@CaryLandholt I created a separate issue for your report because I think it's a different case

**Comment by CaryLandholt** [comment]
Thanks, faktory also output the following:
```shell
E 2018-11-15T21:25:51.227Z error=read tcp 192.168.32.2:7419->192.168.32.19:51122: i/o timeout Closing connection
```

Although I was still able to access localhost:7420

**Comment by mperham** [comment]
Is fwn setting the TCP keep alive on the socket when opening it?

**Comment by jbielick** [comment]
@mperham I don't think it is (not on by default). I saw that in the other clients. I suppose we should be enabling it here—that sound right?

**Comment by mperham** [comment]
I would recommend it.

**Comment by mperham** [comment]
Aw it didn’t attach my photo. </joke>

**Comment by CaryLandholt** [comment]
Will do @jbielick

**Comment by CaryLandholt** [comment]
@jbielick looks like this did resolve my issue.  Thanks!
