### ISSUE TITLE
README script doesn't work

### ISSUE THREAD

**Issue by mperham** [jbielick/faktory_worker_node#25]
Hi Josh, I'm trying out your library and writing a blog post on it.  Since I'm a JS neophyte, I'm struggling with your sample code, especially starting a new worker process:

```js
const faktory = require('faktory-worker');

faktory.register('adder', async (a, b) => {
  console.log(a, " + ", b, " = ", a+b)
});

await faktory.work();
// send INT signal to shutdown gracefully
```

Output:

```
10:00:32 worker.1  | /Users/mikeperham/src/blog/fworker.js:7
10:00:32 worker.1  | await faktory.work();
10:00:32 worker.1  | ^^^^^
10:00:32 worker.1  | 
10:00:32 worker.1  | SyntaxError: await is only valid in async function
10:00:32 worker.1  |     at new Script (vm.js:84:7)
10:00:32 worker.1  |     at createScript (vm.js:264:10)
10:00:32 worker.1  |     at Object.runInThisContext (vm.js:312:10)
10:00:32 worker.1  |     at Module._compile (internal/modules/cjs/loader.js:684:28)
10:00:32 worker.1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
10:00:32 worker.1  |     at Module.load (internal/modules/cjs/loader.js:620:32)
```

How do I wrap the await at the top-level?

**Comment by jbielick** [comment]
Sorry, Mike, this is an annoying shortcut a lot of node library docs take to not distract the reader from the usual amount of javascript async syntax noise.

To create a closure that supports `await` usage, you'll need an `async function` wrapper. I typically start with a `async` IIFE like so:

```javascript
const faktory = require('faktory-worker');

(async () => {
  // await can be used inside here
  await faktory.work();
})().catch((e) => console.error(e));
// catch any async errors that occur inside of your closure and report them
```

**Comment by jbielick** [comment]
You might be able to omit the `await` in that example as well, as `faktory.work();` continually fills the event loop and prevents the process from exiting. It doesn't return until the workers shutdown so there's really seldom a usage for `await`ing `.work()`. 

I'll update the docs accordingly.
