### ISSUE TITLE
`Connect ETIMEDOUT` in Windows 10 worker process

### ISSUE THREAD

**Issue by jbielick** [jbielick/faktory_worker_node#30]
Hi @jbielick -- I have been coming across this issue a lot recently on a Windows worker. I just updated from 2.2.0 to 3.02, and am still seeing this issue.

Jobs process normally for a while, and then I hit the error described above which takes down the entire process. 

On the worker, I'm running Windows 10, Node 10.16, faktory-worker-node 3.02. I do _not_ see this same issue on my ubuntu workers. Do you have any further insight into this issue on this platform specifically? Is there something I can do in my code to be more defensive? I didn't want to open a new issue yet since all of the context is here.

Here is an example output log from my app: https://pastebin.com/3r9Sq3KT
It shows the process working for a while sending a variety of ACKs and FAILs, and then crashing.

Here is how I'm initiating the worker with a few small redactions. I'm not very great with Node, so I'm including this in case it shows something obviously incorrect.

```js
const faktory = require('faktory-worker');
const worker = require('./worker-__');
const colors = require('colors');

const concurrency = parseInt(process.argv[2]) || 4;

// Setup the worker server & register the faktory worker(s).
(async () => {
  faktory.register('Harvest::__::Scraper', async (zipCode, section, aspect, rim, url=null) => {
    if (url) {
      await worker.extractSingleProduct(zipCode, section, aspect, rim, url);
    } else {
      await worker.run(zipCode, section, aspect, rim);
    }
  });
  faktory.register('Harvest::__::Scraper::InCartPricing', async (zipCode, section, aspect, rim, listing) => {
    await worker.inCartPricing(zipCode, section, aspect, rim, listing);
  });

  // MIDDLEWARE
  faktory.use(async (ctx, next) => {
    const start = new Date(Date.now()).toISOString();
    try {
      console.log(`${start} ${ctx.job.jid} ${ctx.job.jobtype} Start ${ctx.job.args}`);
      await next();
      const end = new Date(Date.now()).toISOString();
      console.log(`${end} ${ctx.job.jid} ${ctx.job.jobtype} ACK ${ctx.job.args}`.green);
    } catch (e) {
      const errTime = new Date(Date.now()).toISOString();
      console.log(`${errTime} ${ctx.job.jid} ${ctx.job.jobtype} FAIL ${ctx.job.args}`.red);
      throw e;
    }
  });

  await faktory.work({
    queues: ['www.__.com'],
    concurrency : concurrency
  });
})()

```

Please let me know if you'd like me to create a separate issue or provide more information, or if there is something I should change on my side.

_Originally posted by @ttilberg in https://github.com/jbielick/faktory_worker_node/issues/23#issuecomment-496991319_

**Comment by jbielick** [comment]
Thanks for the logs. FYI you can get really detailed logs (almost too much detail) by running the worker with an ENV variable `DEBUG=faktory*`—that would show lines for opening a new connection, call and response, etc.

From the looks of it, I'm thinking it's encountering an ETIMEDOUT (timeout) while attempting to _create a new connection_ to the server. This is normal, as it uses a connection pool and opens new connections when the pool is under load. This is confusing, because you already have a few open sockets to the server at that point.

Are you able to reproduce this error with `DEBUG=` on? That would help corroborate the above suspicion. 

I think there might be one or two things that could help in the meantime. I'm sure you've noticed, but In node error handling is not straightforward because of async operations. in certain circumstances an uncaught error in an async operation can kill the whole process. Could you try one or two things and see if it helps keep your process from crashing?

Something like this will catch _all_ uncaught errors, so don't keep it around after debugging. This might log that connect timeout error while keeping the process running.

```
process.on('uncaughtException', (err) => {
  console.error(err);
})
```

I'd also suggest using a process manager that can keep your process running long-term and restart it if it fails. I think in windows this might be a window service. Potentially `pm2` could help here (a tutorial I found and have not read: https://blog.cloudboost.io/nodejs-pm2-startup-on-windows-db0906328d75?gi=fd7b6c3f1799).

**Comment by ttilberg** [comment]
A few more notes I meant to include:
- I'm currently running Faktory Server 1.0.0 in a Docker container. It's on a remote network connected by site-to-site VPN that has reasonable performance, but is of course less than being on the local network.
- At least one of the Ubuntu workers I run are in the same network position and hasn't seen this issue
- The job that this specific worker is attached to also pushes jobs back to Faktory -- so perhaps this is happening on the client.push part -- the stacktrace doesn't make that clear.

Here's the code that pushes jobs back -- it would happen once for each job processed by the node worker, currently experiencing concurrency of 6 in my example.

```javascript
async function writeToFaktory(zip, section, aspect, rim, html) {
  const client = await faktory.connect();
  await client.push({
    jobtype: 'Harvest::__::Scraper::PageToDb',
    args: [zip, section, aspect, rim, html]
  });
  await client.close();
}

```

**Comment by ttilberg** [comment]
After reading your notes above, I was starting to feel like that push could in fact be the culprit, since it doesn't have any error handling -- but then I remembered that's intentionally, as I want the error to bubble up to the worker server and `FAIL`. However, perhaps there is some conflict happening here, as the connection pool may be getting abused in an unexpected way.

I'll see if i can get some debug logs going for this issue as well. And thanks for the PM2 suggestion. I was trying to figure out how I could get some sort of unattended restart action going!

**Comment by jbielick** [comment]
Hmm. So each time it pushes a job it tries to connect to factory? That raises a couple flags. If it were possible to use the same faktory client for every call to `writeToFactory`, that would be much better. Opening and closing that many connections could cause some strange behavior as they're executing very fast and definitely traveling through a proxy or two (site-to-site VPN).

If you create a single faktory client, you could provide it to your job functions in the middleware.

```js
(async () => {
  const client = await faktory.connect();
  
  // give all jobs a handle to the faktory client
  faktory.use((ctx, next) => {
    ctx.faktory = client;
    return next();
  });
  
  await faktory.work(...);

})().catch((err) => console.error(err));
```

That way you could share one connection pool (the client) between all your workers. That would avoid creating a new pool each time.

**Comment by jbielick** [comment]
Here's a more descriptive example from the readme that's pretty analogous.

```js
const { createPool } = require('generic-pool'); // any pool or connection library works
const faktory = require('faktory');

const pool = createPool({
  create() { return new Client(); },
  destroy(client) { return client.disconnect(); }
});

faktory.use(async (ctx, next) => {
  ctx.db = await pool.acquire();
  try {
    // middleware *must* return next() or await next()
    // this invokes the downstream middleware (including your job fn)
    await next();
  } finally {
    // return connection to pool
    pool.release(ctx.db);
  }
});

faktory.register('TouchRecord', (id) => async ({ db }) => {
  const record = await db.find(id);
  await record.touch();
});
```

**Comment by ttilberg** [comment]
Thanks for your rapid response and suggestions. I've seen that example in the readme and had these suspicions, but didn't have enough experience with Node to really work it out. I'm going to make this change and I'll report back whether I still see this issue or not.

**Comment by jbielick** [comment]
My pleasure. Let's keep this open while experimenting / debugging and see if the reduction in connection attempts resolves it.

In any event, I might need to expose or propagate the socket errors so that users can listen for them and "catch" them instead of crashing the whole process. I'll look into that.

**Comment by ttilberg** [comment]
Here is a sample of the log generated right before it crashed. I don't want to capture the whole thing, as the args I pass back and forth are sometimes quite large (120 KB for example). The debug output shows the full arg list both as a send, and the confirmation from the server -- so it's unwieldy to store to disk. This may seem excessive (as opposed to storing the data somewhere and passing a reference to the data to Faktory) but this process has worked really well for me for almost a year, and reduces the need for extra infrastructure. (Perhaps I do need to consider going this route after all.)

My main takeaway from this seems to be that we are trying to push a normal job related message to Faktory, which fails due to timeout (as I previously mentioned I wish to happen so that we can retry the job). This then turns into trying to send a `FAIL` to Faktory, as this is the error that the job generated. This message also fails to send due to timeout, which I think triggers the crash.

My hope/expectation would be that if FWN is unable to communicate with the Faktory server, it would just abandon the job and keep on business as usual. Eventually Faktory Server would realize it hasn't had response to that job and re-que it. However, this leaves the unanswered question of "So what am I supposed to do with this job then if I can't report back to the Faktory Server?" And perhaps this isn't as easy to answer in a scenario where you have to ensure that a job is processed exactly one single time.

```
# ...
# Up to this point, there is a lot of noise with successful conversations pulling and pushing jobs to Faktory for a few hours.
#
# The args are large (~120 KB for some), as I'm sending certain selections of DOM elements back to Faktory to parse in Ruby.
# so I'm only sending this last part of the debug log for now. 
#
# The last few messages appear to be attempts to send a push to Faktory, without acknowledgement from the server leading to this:
#
  faktory-worker:connection-pool +connection +57s
  faktory-worker:connection connecting +859ms
  faktory-worker:connection-pool +connection +803ms
  faktory-worker:connection connecting +803ms
  faktory-worker:client:heart BEAT +15s
  faktory-worker:connection SEND: BEAT {"wid":"4154b94d"} +2s
  faktory-worker:connection OK +161ms
  faktory-worker:connection client='BEAT {"wid":"4154b94d"}', server='OK' +1ms
  faktory-worker:connection timed out +683ms
  faktory-worker:connection-pool +connection +3s
  faktory-worker:connection connecting +82ms
  faktory-worker:connection timed out +743ms
2019-05-30T02:17:55.151Z e8a6fec3ac683803b840c654 Harvest::__::Scraper FAIL 73112,285,30,21
  faktory-worker:connection SEND: FAIL {"message":"ResourceRequest timed out","backtrace":["TimeoutError: ResourceRequest timed out","    at ResourceRequest._fireTimeout (C:\\Users\\tim\\scrape-faktory\\node_modules\\generic-pool\\lib\\ResourceRequest.js:62:17)","    at Timeout.bound (C:\\Users\\tim\\scrape-faktory\\node_modules\\generic-pool\\lib\\ResourceRequest.js:8:15)","    at ontimeout (timers.js:436:11)","    at tryOnTimeout (timers.js:300:5)","    at listOnTimeout (timers.js:263:5)","    at Timer.processTimers (timers.js:223:10)"],"jid":"e8a6fec3ac683803b840c654"} +1s
2019-05-30T02:17:55.874Z c9c9398f65ebd2f6f243a0bd Harvest::__::Scraper FAIL 37934,245,75,16
  faktory-worker:connection-pool +connection +3s
  faktory-worker:connection connecting +722ms
2019-05-30T02:17:58.420Z 1eff6d2af2f1c7c80dcdce71 Harvest::__::Scraper FAIL 80525,315,30,18
  faktory-worker:connection-pool +connection +3s
  faktory-worker:connection connecting +3s
  faktory-worker:connection timed out +2s
{ TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (C:\Users\tim\scrape-faktory\node_modules\generic-pool\lib\ResourceRequest.js:62:17)    at Timeout.bound (C:\Users\tim\scrape-faktory\node_modules\generic-pool\lib\ResourceRequest.js:8:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) name: 'TimeoutError' }
{ TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (C:\Users\tim\scrape-faktory\node_modules\generic-pool\lib\ResourceRequest.js:62:17)    at Timeout.bound (C:\Users\tim\scrape-faktory\node_modules\generic-pool\lib\ResourceRequest.js:8:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) name: 'TimeoutError' }
  faktory-worker:connection OK +5s
  faktory-worker:connection client='FAIL {"message":"ResourceRequest timed out","backtrace":["TimeoutError: ResourceRequest timed out","    at ResourceRequest._fireTimeout (C:\\\\Users\\\\tim\\\\scrape-faktory\\\\node_modules\\\\generic-pool\\\\lib\\\\ResourceRequest.js:62:17)","    at Timeout.bound (C:\\\\Users\\\\tim\\\\scrape-faktory\\\\node_modules\\\\generic-pool\\\\lib\\\\ResourceRequest.js:8:15)","    at ontimeout (timers.js:436:11)","    at tryOnTimeout (timers.js:300:5)","    at listOnTimeout (timers.js:263:5)","    at Timer.processTimers (timers.js:223:10)"],"jid":"e8a6fec3ac683803b840c654"}', server='OK' +1ms
  faktory-worker:worker FAIL e8a6fec3ac683803b840c654 +24s
  faktory-worker:connection SEND: FETCH www.tires.com +1ms
  faktory-worker:connection error: { Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' } +2s
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at Connection.onError (C:\Users\tim\scrape-faktory\node_modules\faktory-worker\lib\connection.js:190:10)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

C:\Users\tim\scrape-faktory>
```

Let me know if you'd like me to send you more details logs. I'm a bit hesitant to `>` them to disk, but I'm happy to try to get you more information if you think it would be helpful.

**Comment by jbielick** [comment]
Is this before or after switching to using a single pool / not creating and tearing down pools for each job?

**Comment by ttilberg** [comment]
After.

**Comment by jbielick** [comment]
Well, the "good" news here is that we're getting a new error 😁 

The new error is a timeout in which the code is requesting a connection from the connection pool, but it has to wait too long to get one. This could be caused by a few things:

1. the server is responding too slow, or hanging altogether during a response (could be to an issue with the server's disk, memory, cpu, etc).
2. the server is fine, but there are much more worker threads than there are connections in the pool. That is, the pool size should be `concurrency+2` or more so that there's at least one socket for every worker that could be asking for one to use.

I'd try and make sure of #2 because that's easy to try out. `Client` accepts a `poolSize` parameter during construction. I think you could do:

`const client = faktory.connect({ poolSize: concurrency + 2 });`

where `concurrency` is the value you're passing to `faktory.work(...)`

I still think there might be some missing error handling somewhere and I'm dialing into where that might need to be. But hopefully this gets you to something more stable.

**Comment by jbielick** [comment]
I'm going to see if exposing the internal faktory client pool to each job so that this wouldn't be as tricky since I can imagine PUSHing jobs inside of jobs is a _very_ common scenario.

What thoughts do you have on how easy this should be?

a context key called `client`, `faktory`? Is there a better way than this?

```js
faktory.register('MyJobThatPushes', (...args) => async ({ client }) => {
  // ... work
  await client.job().push(...);
});
```

**Comment by ttilberg** [comment]
For my use case, it's very common to push more jobs from inside a current job -- I'm kind of using Faktory as an easy-to-hook-up Kafka in a sense. I'm not fluent with Node, but I need to use it for a certain subset of tasks, and then pass the obtained data to Ruby where I'm a lot more comfortable.

When I was adding the client injection as you suggested yesterday, I felt bad simply calling it `client` as it's so ambiguous and potentially conflicts with other potential clients (redis, db, etc). I ended up using `faktoryClient` in my code, since `faktory` also collided with the var I was importing the FWN library with. 

I did feel like it was a bit awkward setting up a middleware component to inject the Faktory client, so if it could be improved, that would be great.

Perhaps `faktory.client()` could either return the existing instance of a connected `client`, or call `.connect()` if none exists. It makes it easily available, and explicit enough to know what's going on. Then you could push it down the pipe if you need it, or not.

```
faktory.register('MyJobThatPushes', (...args) => {
  const data = work(args)
  await faktory.client().push(data);
});

faktory.register('MyJobThatPushes', (...args) => ({faktoryClient: faktory.client()}) => {
  // ... work that pushes with injected client
});
```

**Comment by ttilberg** [comment]
Or what about exposing `.push()` to the top level `faktory`? Then it can handle the client connection internally if it's needed, and feels a bit less clunky from an API-user point of view. I know when you started this project, you had the client separated all the way out to a separate project. Have you felt good about bringing those concepts closer together? Or do you feel this is this suggesting too much... dual responsibility (or appearance thereof?)

**Comment by ttilberg** [comment]
@jbielick I just wanted to give some updates:

1) I think my faktory server was under stress as you suggested a few points ago. Some changes in the data being processed is causing a lot more jobs to get pushed, and I was having issues keeping up with workers. I think there was just a lot of congestion overall, and as mentioned, there are some network hops involved.

If it were possible to relax the timeout, or otherwise self heal, I think this would still be very helpful.

2) I looked into PM2, and it does work just fine on Windows. Thank you for this suggestion, it has essentially made the crashing-due-to-timeouts issue completely painless. It's reporting about 6 restarts over 24 hours. Thanks a ton for this suggestion.

**Comment by jbielick** [comment]
> When I was adding the client injection as you suggested yesterday, I felt bad simply calling it client as it's so ambiguous and potentially conflicts with other potential clients (redis, db, etc). I ended up using faktoryClient in my code, since faktory also collided with the var I was importing the FWN library with.
> I did feel like it was a bit awkward setting up a middleware component to inject the Faktory client, so if it could be improved, that would be great.

Agreed. I'll do some thinking on this.

> Perhaps faktory.client() could either return the existing instance of a connected client, or call .connect() if none exists. It makes it easily available, and explicit enough to know what's going on. Then you could push it down the pipe if you need it, or not.

This is a little tricky when it comes to hiding the fact that you opened a connection pool. I imagine it would be a little _too easy_ and people would forget to close that pool / do cleanup, etc. I think this could be avoided / alleviated if the above was solved.

> Have you felt good about bringing those concepts closer together? Or do you feel this is this suggesting too much... dual responsibility (or appearance thereof?)

I'm glad they're not managed separately—it was just a release / dependency nightmare for me personally and I only did so in the beginning because I thought it might help me focus on getting one piece right at a time. That and if someone could write a better API using the client, I'm all for that.

> I think my faktory server was under stress as you suggested a few points ago. Some changes in the data being processed is causing a lot more jobs to get pushed, and I was having issues keeping up with workers. I think there was just a lot of congestion overall, and as mentioned, there are some network hops involved.

That makes sense. Given the refusal to connect when opening a new connection it seemed like a network saturation or a overloaded server.

> If it were possible to relax the timeout, or otherwise self heal, I think this would still be very helpful.

**Agreed. Definitely going to do this and another change or two to avoid things crashing like they did.**

> I looked into PM2, and it does work just fine on Windows. Thank you for this suggestion, it has essentially made the crashing-due-to-timeouts issue completely painless. It's reporting about 6 restarts over 24 hours. Thanks a ton for this suggestion.

Glad to hear it! That can take a lot of stress off :) Are the restarts you're seeing due to timeouts?

**Comment by ttilberg** [comment]
Yes, 100% of the time it's the error we've previously reviewed. Thanks for your time!

**Comment by jbielick** [comment]
`v3.0.3` is published. Timeout has been increased to 10s (I'd like to make this a user-configured value) and uncaught error events are no longer emitted and uncatchable (see #31).

Still thinking about how to expose the client to jobs in middleware context.
