### ISSUE TITLE
`Unhandled 'error' event` when trying to connect to down faktory server

### ISSUE THREAD

**Issue by yoannduc** [jbielick/faktory_worker_node#31]
Hi @jbielick 

I am using faktory and this lib in a project and it worked fine at first. But then I came across some issues with error handling.

With architecture in mind, I want my project to keep running if faktory server is down (the other parts of the project which are not faktory dependant).

However, if faktory worker can't be found at `options.host:options.port`, the lib crashes the application. This is due to unhandled 'error' event.

This is likely due to this line:

https://github.com/jbielick/faktory_worker_node/blob/9e9446946313a0f3b545ece2feaeb9df677b1e07/lib/connection.js#L190

Which make the `client.connect()` uncatchable.

The error: 

```
events.js:174
     throw er; // Unhandled 'error' event
     ^

Error: connect EHOSTUNREACH 172.12.12.10:7419
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
Emitted 'error' event at:
   at Connection.onError (/usr/src/app/node_modules/faktory-worker/lib/connection.js:191:10)
   at Socket.emit (events.js:194:15)
   at emitErrorNT (internal/streams/destroy.js:82:8)
   at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
   at process._tickCallback (internal/process/next_tick.js:63:19)

[nodemon] app crashed - waiting for file changes before starting...
```

I'm using node version: 10.15 with `facktory-worker` package version: 3.0.2

Here is the client helper code that makes the whole application crash:

```js
const {Client} = require('faktory-worker')

module.exports = (config, logger) => {
  const client = new Client(config)

  return client
    .connect()
    .then(() => {
      logger.info('Connection to faktory has been established successfully.')
      return client
    })
    .catch(err => {
      logger.error(`Unable to connect to faktory: ${err}`)
      return err
    })
}
```

I played around with my `faktory-worker` package in my `node_modules` directory and commenting this particular line make the `connect` function catchable once again

**Comment by jbielick** [comment]
Sorry about this. You're absolutely right—the error emit is causing issues and isn't really listenable. I had forgotten the significance of this event name when writing. I've updated to not emit an uncaught `error` and published at `v3.0.3`. Let me know if you have any issues after updating.

**Comment by yoannduc** [comment]
Hi @jbielick, thank you for the quick fix. Do you know when will the `v3.0.3` be available on npm ? 🙂

**Comment by jbielick** [comment]
Yoan, I'm sorry, I thought `publish` was a part of my release scripts. It's now available on npm.

```
faktory-worker@3.0.3 | MIT | deps: 6 | versions: 33
A faktory worker framework for node apps
https://github.com/jbielick/faktory_worker_node#readme

keywords: faktory, client, node, server, job, background, async

bin: faktory-work, faktory-cluster

dist
.tarball: https://registry.npmjs.org/faktory-worker/-/faktory-worker-3.0.3.tgz
.shasum: 6c67a57fd67c9ce8fbc4593137af171dc8153d72
.integrity: sha512-uS8dz8VhEYynSVqNDsR/MrbV+WzyLn8U3OD9Eht/w32d+tNkrfc9QDuk5jb7bkGsiObV+9CA7wZmpEnJvkGczQ==
.unpackedSize: 127.1 kB

dependencies:
commander: ^2.11.0   debug: ^4.1.0        generic-pool: ^3.4.2 koa-compose: ^4.0.0  redis-parser: ^3.0.0 uuid: ^3.1.0         

maintainers:
- jbielick <jbielick@gmail.com>

dist-tags:
latest: 3.0.3  

published a minute ago by jbielick <jbielick@gmail.com>
```

**Comment by yoannduc** [comment]
Thank you !
