### ISSUE TITLE
Workers Seem To Hang After Upgrade to 4.3.0

### ISSUE THREAD

**Issue by nmstone** [jbielick/faktory_worker_node#312]
node.js version:
`16.15.1`

npm/yarn version:
`1.22.10` (yarn)

faktory-server version: 
`1.5.1`

`faktory-worker` package version:
`4.1.4` -> `4.3.0`

Hi there. Thanks for the excellent project!

I ran into an issue after upgrading from 4.1.4 -> 4.3.0 where workers appear to hang. I am unable  to replicate in a small example and the issue does not appear consistently in my environment, but after a good amount of debugging, I am confident it comes from the upgrade in some way. 

The workers do a good amount of IO and are on the default concurrency, and the `work` function code has not changed between version upgrades. The hanging only shows up in `4.3.0`, although I think the hanging is probably a symptom of something else rather than the node workers actually hanging.

Sorry to be so vague but I am confused myself and still collecting information! I figured i'd at least create an issue in case someone else has issues after upgrading.

If I can provided any specific information let me know. I'll need to look at the version diffs as well and see if anything sticks out.

**Comment by jbielick** [comment]
@nmstone Are you able to run the workers with an ENV variable like `DEBUG=faktory*`? That would provide very verbose debug logging (be warned that the log volume will be high) and record logs until the workers hang? That might point me in the right direction.
