### ISSUE TITLE
CLI Load Registrations and Registration Best Practice

### ISSUE THREAD

**Issue by imack** [jbielick/faktory_worker_node#341]
node.js version: 14.17.1
npm/yarn version: 7.6.1
faktory-server version: 1.6.1
`facktory-worker` package version:4.4.0

Hi,

I see the CLI option for starting using `node_modules/.bin/faktory-work`, however, whenever I start the process that way any jobs get an error saying `undefined: No jobtype registered: <jobname>`. 

This makes sense as the command line tool doesn't seem to allow for any jobs to be registered. Am I missing something about how jobs can be registered to the cli spawned worker? 

Related, is the a best practice for how users load a potentially large number of registrations attached to a worker? For example do people create a `jobs` or `tasks` folder where each file contains a `worker.register()` call and `require` the whole folder, or have all the register calls in one `worker.js` file that then call out to other modules?

**Comment by jbielick** [comment]
Hi there,

Thanks for opening the issue and discussion. Allowing job code to be required by the CLI was a longstanding item on the roadmap. Since you mentioned it, I've added a barebones implementation and [released it in 4.5.0](https://github.com/jbielick/faktory_worker_node/releases/tag/v4.5.0).

I think there are a couple ways of structuring the job code and making it require-able, but if you want my opinion I would do something like this:

```
jobs/
├── one.js
└── two.js
```

and require them like this:

```
faktory-work -r ./jobs/*
```

I'm open to suggestions here and would like to keep it simple. Any thoughts?

**Comment by imack** [comment]
Hi @jbielick, appreciate the reply. Thanks for the release, that solves some implementation things for me. 

I think that looks good. Only note would be that maybe `/jobs/*` should be a default value for the import which can be overridden with that flag?

I'm coming from a `Sidekiq/Ruby` background which just default imports anything in `app/workers`, so this setup seem similar.

**Comment by imack** [comment]
hmm, seems to only be requiring the first item in the directory. ie. the asterix expands the files to something like `-r ./jobs/faktory/one.ts ./jobs/faktory/two.ts` and only the first gets picked up by your change.

**Comment by jbielick** [comment]
You're absolutely right. I should have checked on needed to repeat the `-r` flag when using a glob. Is it reasonable to have a structure like this?

```
jobs/
├── index.js
├── one.js
└── two.js
```

in which index.js is something like:

```
const faktory = require("faktory-worker");

faktory.register('one', require('./one'))
faktory.register('two', require('./two'))
```

or is that too tedious?

**Comment by imack** [comment]
feels like the `index.js` method is a bit tedious (but fine for now) and I'm 100% going to forget to put something in the `index.js` at some point in the future. That said, I'd like to poke around for a bit, get to know things and make a more learned suggestion.

**Comment by jbielick** [comment]
> feels like the `index.js` method is a bit tedious (but fine for now) and I'm 100% going to forget to put something in the `index.js` at some point in the future. That said, I'd like to poke around for a bit, get to know things and make a more learned suggestion.

That sounds great. Do let me know if you have some suggestions after working with it.

**Comment by imack** [comment]
I checked the Ruby and Go official libraries, seems like they take different approaches best aligned with the respective platforms. 

I think what we have so far is fine and maybe a strong defaults isn't necessarily the right "node" answer. I think the command line import unblocks what I need it for, so I'm content to close this for now unless a better Node dev than me has more thoughts. Listing imports is fine for me.

**Comment by wzulfikar** [comment]
Hey, I have this `jobs/index.js` file that will load the job files from `jobs` directory so I don't have to manually update the index file. Thought it might be useful to share here.

```js
// jobs/index.js

const fs = require("fs");
const faktory = require("faktory-worker");

const jobsDir = process.argv[process.argv.indexOf("-r") + 1];

fs.readdir(jobsDir, (err, files) => {
  files.forEach((file) => {
    if (err) throw new Error(err);
    if (file == "index.js") return;

    const job = require(`${jobsDir}/${file}`);
    faktory.register(job.name, job);

    console.log("- Job registered:", job.name);
  });
});
```

Here's an example of a job file:
```js
// jobs/ResizeImage.js

async function ResizeImage({ id, size }) {
  console.log("[ResizeImage] Job processed:", { id, size });
}

module.exports = ResizeImage;
```

A quick preview (taken from my [demo repo](https://github.com/wzulfikar/faktory-node-require-jobs)):

https://user-images.githubusercontent.com/7823011/189620374-df5a0f68-8cf2-4258-b067-1f5d574e9fcf.mp4
