### ISSUE TITLE
Surprisingly slow password hashing

### ISSUE THREAD

**Issue by ThePletch** [jbielick/faktory_worker_node#360]
I've been doing some application profiling of our system and noticed that generating a new Faktory connection is surprisingly slow (~400ms), most of which is spent doing the default 4000 (!) hash/salt iterations on the configured password to ensure we have the same password as the scheduler.

Would it be possible to memoize the [`hash` function](https://github.com/jbielick/faktory_worker_node/blob/8e811179d4b5e28a43f2bc0f6f511c2eba2c38a2/src/utils.ts#L44), so it only needs to be run once per process for the same password + salt + iterations parameters? If so, I can look into opening a PR for that.

**Comment by jbielick** [comment]
This is very interesting! Thanks for the report.

If I recall correctly, the server sends a random integer for `iterations`, upon each connection. If the iterations is different each time we connect, will caching help at all? Unless you're talking about hashing the first 4000 iterations and always performing the remaining?

Reference:
see (`rand.Intn(4096)`):

```go
	// 4000 iterations is about 1ms on my 2016 MBP w/ 2.9Ghz Core i5
	iter := rand.Intn(4096) + 4000 //nolint:gosec
```
https://github.com/contribsys/faktory/blob/047b418906693867d7eb8a3b974c75d55becfb70/server/server.go#L196-L197

**Comment by ThePletch** [comment]
ah dangit, i missed the randomization. and i doubt i'll convince mike perham that 4000 iterations is not 1ms in most cloud environments, presumably due to cpu cache being harder to utilize in a shared environment.

**Comment by ThePletch** [comment]
looking like i may have misinterpreted some profiling - the stat i gave was actually "400ms per 1 minute of cpu wait time," which is a much less outrageous figure. apologies for the false alarm.
