### ISSUE TITLE
Cpu 100% if worker cannot connect to faktory server

### ISSUE THREAD

**Issue by laviniuolaru** [jbielick/faktory_worker_node#38]
node.js version: 12

npm/yarn version: 6

faktory-server version: 1.0.1

`facktory-worker` package version: 3.1.0

#### Code sample:

```js
faktory.register(jobTypes.export, async (data) => {
    await job(data);
});

console.log(`🚀 Waiting for jobs on ${htmlQueue}...`);
faktory.work({ queues: htmlQueue, concurrency });
```

#### Steps to reproduce the behavior or a test case:

If you change FAKTORY_URL to a domain that does not exists or faktory server is down generic-pool will keep trying to connect to that server and keep CPU to 100% or more. 

The problem is that the create function ConnectionFactory will throw an error and i read here https://github.com/coopernurse/node-pool/issues/197 that this function should not fail or fail with some delay maybe.
I tried something like this

```js
  create() {
    debug('+connection');
    const conn = new Connection(this.port, this.host);
    conn.on('error', this.onError);
    return new Promise(async (resolve, reject) => {
      try {
        const greeting = await conn.open();
        await this.handshake(conn, greeting);
        resolve(conn);
      } catch (e) {
        setTimeout(() => {
          reject(e);
        }, 1000);
      }
    });
  }
```

**Comment by jbielick** [comment]
What's the specific error that's occurring? DNS lookup fails? Invalid hostname? Port is wrong? I imagine some of these will take longer to error and possible not present the tight loop.

**Comment by laviniuolaru** [comment]
Error: getaddrinfo ENOTFOUND queues
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
 errno: 'ENOTFOUND',
 code: 'ENOTFOUND',
 syscall: 'getaddrinfo',
 hostname: 'queues'
 }

i put an hostname that does not exists for this error to appear and the concurency is 6

**Comment by jbielick** [comment]
Great. Thanks for the information—I will start looking into this.

**Comment by jbielick** [comment]
`v3.2.1` address this. Let me know if you have any further issues.

**Comment by laviniuolaru** [comment]
Thank you for this, but the same thing happens if the server is stopped after the connection is established. This works only if the worker starts and the server is down
