### ISSUE TITLE
Support for Faktory Enterprise Features

### ISSUE THREAD

**Issue by MattGirolami** [jbielick/faktory_worker_node#389]
Hi @jbielick ,

I wanted to see if you had any plans to add support for Faktory Enterprise features or if you would accept contributions to add support for Enterprise features. 

My organization may be interested in the Batch and Tracking enterprise features in the future.

**Comment by jbielick** [comment]
Hey,

I don't have concrete plans to implement additional functionality at this time, but contributions are welcome and I will happily review and help release them.
