### ISSUE TITLE
Cpu 100% if connection to server is lost

### ISSUE THREAD

**Issue by laviniuolaru** [jbielick/faktory_worker_node#39]
node.js version: 12

npm/yarn version: 6

faktory-server version: 1.0.1

`facktory-worker` package version: 3.2.1

I started faktory-server and the worker in docker containers, worker connect to server and after some time i stopped the server and started to receive this error from worker and the CPU is 100%. I replied to the other issue after you closed it but i don't know if you saw it. 

Error: getaddrinfo ENOTFOUND queue
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
errno: 'ENOTFOUND',
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'queue'
}

**Comment by jbielick** [comment]
good point! I wondered about that. I have a fix I'll publish in a couple minutes

**Comment by jbielick** [comment]
v3.3.0 is now available on npm
https://www.npmjs.com/package/faktory-worker/v/3.3.0

**Comment by jbielick** [comment]
I went with something similar to what you suggested. Subsequent connection failures sleep on a linear backoff.

https://github.com/jbielick/faktory_worker_node/blob/91d29a1a3f2db72dd1e66fcd6bee5bf3781a68b1/lib/connection-factory.js#L35-L44

I forgot an upper bound to the sleep so 3.3.1 will have a 5s max backoff.

**Comment by jbielick** [comment]
Please reopen if I missed something.

**Comment by laviniuolaru** [comment]
Thank you

**Comment by laviniuolaru** [comment]
```
   await sleep(200 * Math.min([this.attempts, 20])); 
```
for Math.min you have to send each parameter, if you send it an array the result will be NaN and now it await for 0 ms :)

**Comment by jbielick** [comment]
I was wondering when I tested it that it retried so many times :) Thanks for reviewing!
