### ISSUE TITLE
Support TLS

### ISSUE THREAD

**Issue by willhoney7** [jbielick/faktory_worker_node#405]
Hi all! I forked the library so I could add TLS support for our use case. 

You can see my code changes here (also includes some package changes so I could publish our own forked version)

https://github.com/operationalresultsinc/faktory_worker_node/commit/462b3f857c30cc6ff2228fb40f81d1312f749ae8

I'd be happy to contribute a PR. I wanted to add some tests in my code too, but I had trouble getting the suite to run (before my changes). 

Let me know if you want me to open a PR with my current changes.

**Comment by jbielick** [comment]
This is great. I’d happily merge. Could you open a pr?
