### ISSUE TITLE
Guidance on connection reuse

### ISSUE THREAD

**Issue by zekenie** [jbielick/faktory_worker_node#410]
Hello there!

I'm looking for a clarification on a comment you have in your readme ("reuse client if possible! remember to disconnect!")

```js
const faktory = require("faktory-worker");

(async () => {
  const client = await faktory.connect();
  await client.job("ResizeImage", { id: 333, size: "thumb" }).push();
  await client.close(); // reuse client if possible! remember to disconnect!
})().catch((e) => console.error(e));
```

Would it be a good idea in a web process that produces jobs to pool these clients with some kind of connection pool? or is it more of an optimization?

Thank you

**Comment by jbielick** [comment]
Hi @zekenie 👋🏻 

Great question. There is connection pooling built into the `Client` object. For a web process that runs continuously, it would be best to start/connect the Client upon app startup, and call `close()` during process shutdown. That is, you can safely use the same `Client` for processing many requests concurrently. The `Client#push` and similar methods will automatically check out a connection from the pool when communicating with the Faktory server. The connection pool within Client will scale up and down based on demand. 

https://github.com/jbielick/faktory_worker_node/blob/74672564cfd1f6e34fde6399e8f18271efe0a37c/src/client.ts#L84
