### ISSUE TITLE
Function `push` in Client should return Promise<string>

### ISSUE THREAD

**Issue by scrofungulus** [jbielick/faktory_worker_node#42]
The Client function [`push`](https://github.com/jbielick/faktory_worker_node/blob/master/lib/client.js#L200) is asynchronous and should return a `Promise` that resolves to `string`.

**Comment by jbielick** [comment]
Please use the issue template or provide some amount of context about the problem you're having.

**Comment by scrofungulus** [comment]
@jbielick Apologies. 

The problem is that the `push` function in `lib/client.js` is documented as returning a `String`: 
```
  /**
   * Pushes a job payload to the server
   * @param  {Job|Object} job job payload to push
   * @return {String}         the jid for the pushed job
   */
  async push(job) {
    const payload = job.toJSON ? job.toJSON() : job;
    const payloadWithDefaults = Object.assign({ jid: Job.jid() }, Job.defaults, payload);
    await this.sendWithAssert(['PUSH', encode(payloadWithDefaults)], 'OK');
    return payloadWithDefaults.jid;
  }
```

Because the function is `async` it truly returns `Promise<String>`. The main issue is that tooling/language servers used by text editors look at the JsDoc for the function and assert a `String` return type which causes downstream issues / confusion when using the library / building abstractions on top of it.

**Comment by jbielick** [comment]
Ah, I see. Thanks for the info. I thought you were talking about typescript definitions. I've pushed `v3.3.4` with changes to annotate the right return value. Let me know if you have any issues with the new annotations.
