### ISSUE TITLE
TypeScript project breakage due to typings in 3.3.7+

### ISSUE THREAD

**Issue by MarkMurphy** [jbielick/faktory_worker_node#71]
`facktory-worker` package version: 3.3.7+
```ts
import faktory from 'faktory-worker'
```
yields the following typescript error: 

```
'faktory' is declared but its value is never read. ts(6133)
```
I am in fact using it. 

This is because of the change from `export class faktory` to `export interface faktory` in index.d.ts

An interface can only be used as a type.

**Comment by jbielick** [comment]
That's strange. In the TypeScript branch I'm still using `export interface FaktoryControl {` (not a class).

Could you give `4.0.0` a try? No major API changes, just migrated to TypeScript.

**Comment by MarkMurphy** [comment]
`WorkerOptions` is missing as a named export where it is was previously available.

```ts
import { WorkerOptions } from 'faktory-worker'
```

**Comment by jbielick** [comment]
`WorkerOptions` and `ClientOptions` types now exported in `4.0.1`. Thanks, @MarkMurphy !
